### ISSUE TITLE
async_listen with run_immediately is deprecated

### ISSUE THREAD

**Issue by tomlut** [pnbruckner/ha-clock-drift#1]
Testing on the 2024.5.b0 core beta release produces this error:

```
Detected that custom integration 'clock_drift' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/clock_drift/__init__.py, line 68: hass.bus.async_listen(EVENT_HOMEASSISTANT_STARTED, startup, run_immediately=True), please report it to the author of the 'clock_drift' custom integration
```

See: https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job/

**Comment by pnbruckner** [comment]
Interesting. First, you must be using an older version of this integration, since that call is now on line 113. Second, that blog post is about adding jobs, not calling async_listen. Third, accepting the argument won't be removed until next year. Fourth, I had mostly forgotten about this integration! lol

It seems they changed the default from False to True, and then deprecated it. They didn't make it easy for custom integrations to figure out what the right thing to do is (if they want to work with a range of HA versions. Luckily, this is the only custom integration of mine that uses that feature.) I suppose I could just add a test for HA version, and only add the argument for versions where the default was False. Oh, I just checked. That was anything before _2024.5.0b0!_ So, this is brand spanking new.

I'll go ahead and make that change now. When I commit the change, you can give it a try if you like.

**Comment by pnbruckner** [comment]
Ok, you can give 1.0.0b2 (694bb278664526ad7fd5de9bed48f3652dabb8ae) a try.

**Comment by tomlut** [comment]
Thanks Phill. 

Ha, yeah I'm probably running your initial release. Apologies for the wrong link. 

I have updated the files but I'll have to wait for the beta to fix the boot loop I'm experiencing before I can upgrade again.

**Comment by tomlut** [comment]
Upgraded to 2024.5.b1, because they fixed the boot-loop. Clock Drift is all good. Thanks!
